// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: protos/error.proto

package grpcserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category int32

const (
	Category_Retriable Category = 0 // 可以通过重试解决的临时错误（如CAS）
	Category_Business  Category = 1 // 业务错误，不可以通过重试解决
	Category_System    Category = 2 // 系统错误，不可以通过重试解决
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "Retriable",
		1: "Business",
		2: "System",
	}
	Category_value = map[string]int32{
		"Retriable": 0,
		"Business":  1,
		"System":    2,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_error_proto_enumTypes[0].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_protos_error_proto_enumTypes[0]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_protos_error_proto_rawDescGZIP(), []int{0}
}

type GError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code         string    `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`                               // 文本错误码，如：ErrInvalidArgument
	ModuleName   string    `protobuf:"bytes,2,opt,name=ModuleName,proto3" json:"ModuleName,omitempty"`                   // 模块名，如：user
	UserMessage  string    `protobuf:"bytes,3,opt,name=UserMessage,proto3" json:"UserMessage,omitempty"`                 // 用户可读的错误信息
	DebugMessage string    `protobuf:"bytes,4,opt,name=DebugMessage,proto3" json:"DebugMessage,omitempty"`               // 调试信息
	StackTrace   string    `protobuf:"bytes,5,opt,name=StackTrace,proto3" json:"StackTrace,omitempty"`                   // 堆栈信息，一般不用给
	CausedBy     []*GError `protobuf:"bytes,6,rep,name=CausedBy,proto3" json:"CausedBy,omitempty"`                       // 引起本错误的错误
	Category     Category  `protobuf:"varint,7,opt,name=Category,proto3,enum=errorr.Category" json:"Category,omitempty"` // 错误类型
}

func (x *GError) Reset() {
	*x = GError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GError) ProtoMessage() {}

func (x *GError) ProtoReflect() protoreflect.Message {
	mi := &file_protos_error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GError.ProtoReflect.Descriptor instead.
func (*GError) Descriptor() ([]byte, []int) {
	return file_protos_error_proto_rawDescGZIP(), []int{0}
}

func (x *GError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GError) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *GError) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

func (x *GError) GetDebugMessage() string {
	if x != nil {
		return x.DebugMessage
	}
	return ""
}

func (x *GError) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *GError) GetCausedBy() []*GError {
	if x != nil {
		return x.CausedBy
	}
	return nil
}

func (x *GError) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_Retriable
}

var File_protos_error_proto protoreflect.FileDescriptor

var file_protos_error_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x72, 0x22, 0xfc, 0x01, 0x0a,
	0x06, 0x47, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x55,
	0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x63, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x63,
	0x65, 0x12, 0x2a, 0x0a, 0x08, 0x43, 0x61, 0x75, 0x73, 0x65, 0x64, 0x42, 0x79, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x72, 0x2e, 0x47, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x08, 0x43, 0x61, 0x75, 0x73, 0x65, 0x64, 0x42, 0x79, 0x12, 0x2c, 0x0a,
	0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x10, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x72, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x2a, 0x33, 0x0a, 0x08, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x10, 0x02,
	0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_error_proto_rawDescOnce sync.Once
	file_protos_error_proto_rawDescData = file_protos_error_proto_rawDesc
)

func file_protos_error_proto_rawDescGZIP() []byte {
	file_protos_error_proto_rawDescOnce.Do(func() {
		file_protos_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_error_proto_rawDescData)
	})
	return file_protos_error_proto_rawDescData
}

var file_protos_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_error_proto_goTypes = []interface{}{
	(Category)(0),  // 0: errorr.Category
	(*GError)(nil), // 1: errorr.GError
}
var file_protos_error_proto_depIdxs = []int32{
	1, // 0: errorr.GError.CausedBy:type_name -> errorr.GError
	0, // 1: errorr.GError.Category:type_name -> errorr.Category
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_error_proto_init() }
func file_protos_error_proto_init() {
	if File_protos_error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_error_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_error_proto_goTypes,
		DependencyIndexes: file_protos_error_proto_depIdxs,
		EnumInfos:         file_protos_error_proto_enumTypes,
		MessageInfos:      file_protos_error_proto_msgTypes,
	}.Build()
	File_protos_error_proto = out.File
	file_protos_error_proto_rawDesc = nil
	file_protos_error_proto_goTypes = nil
	file_protos_error_proto_depIdxs = nil
}
